name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.4'
      - name: self-update
        run: composer self-update
      - name: composer install
        run: composer install --no-interaction --prefer-source --dev
      - name: Run script
        run: vendor/bin/phpunit --coverage-clover coverage.xml
      - run: ls -ltrR
      - name: Upload reports to Codecov
        run: bash <(curl -s https://codecov.io/bash)